// <auto-generated />
using AppSuite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppSuite.Api.Migrations.AppSuite
{
    [DbContext(typeof(AppSuiteDbContext))]
    [Migration("20260809164352_initialAppSuiteDb")]
    partial class initialAppSuiteDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppSuite.Data.EquipCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EquipCategory");
                });

            modelBuilder.Entity("AppSuite.Data.EquipManuf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("EquipManuf");
                });

            modelBuilder.Entity("AppSuite.Data.EquipModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EquipCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("EquipSubcategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("LotTracked")
                        .HasColumnType("bit");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("ModelNum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Serialized")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EquipCategoryId");

                    b.HasIndex("EquipSubcategoryId");

                    b.HasIndex("MakeId");

                    b.ToTable("EquipModel");
                });

            modelBuilder.Entity("AppSuite.Data.EquipSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EquipCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EquipCategoryId");

                    b.ToTable("EquipSubcategory");
                });

            modelBuilder.Entity("AppSuite.Data.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EquipCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("LotNum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("ModelNum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SerialNum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EquipCategoryId");

                    b.HasIndex("MakeId");

                    b.HasIndex("ModelId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("AppSuite.Data.EquipModel", b =>
                {
                    b.HasOne("AppSuite.Data.EquipCategory", "EquipCategory")
                        .WithMany()
                        .HasForeignKey("EquipCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppSuite.Data.EquipSubcategory", "EquipSubcategory")
                        .WithMany()
                        .HasForeignKey("EquipSubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppSuite.Data.EquipManuf", "EquipManuf")
                        .WithMany("EquipModels")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipCategory");

                    b.Navigation("EquipManuf");

                    b.Navigation("EquipSubcategory");
                });

            modelBuilder.Entity("AppSuite.Data.EquipSubcategory", b =>
                {
                    b.HasOne("AppSuite.Data.EquipCategory", "EquipCategory")
                        .WithMany("EquipSubcategories")
                        .HasForeignKey("EquipCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipCategory");
                });

            modelBuilder.Entity("AppSuite.Data.Equipment", b =>
                {
                    b.HasOne("AppSuite.Data.EquipCategory", "EquipCategory")
                        .WithMany()
                        .HasForeignKey("EquipCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppSuite.Data.EquipManuf", "EquipManuf")
                        .WithMany()
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppSuite.Data.EquipModel", "EquipModel")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipCategory");

                    b.Navigation("EquipManuf");

                    b.Navigation("EquipModel");
                });

            modelBuilder.Entity("AppSuite.Data.EquipCategory", b =>
                {
                    b.Navigation("EquipSubcategories");
                });

            modelBuilder.Entity("AppSuite.Data.EquipManuf", b =>
                {
                    b.Navigation("EquipModels");
                });
#pragma warning restore 612, 618
        }
    }
}
